version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: noithat_postgres
    restart: always
    environment:
      POSTGRES_USER: noithat_admin
      POSTGRES_PASSWORD: noithat_password
      POSTGRES_DB: noithat_db
    ports:
      - '5435:5432'
    volumes:
      - noithat_db_data:/var/lib/postgresql/data

volumes:
  noithat_db_data:
